### ISSUE TITLE
add a way of staging to it

### ISSUE THREAD

**Issue by manzke** [gesund-zusammen/gesund-zusammen.github.io#36]
we are live, so we can't break the site anymore. :)

**Comment by sebbsan** [comment]
* add deployment via S3
* deploy branches to S3 
* add staging... alias to S3 deployment
* make sure staging is not indexed by robots - probably add simple authentication / password protection

**Comment by sebbsan** [comment]
sources branch is now deployed to staging 
when making a release, it deploys to production

**Comment by manzke** [comment]
nice work! 👍
