### ISSUE TITLE
Add our Twitter stream to the page

### ISSUE THREAD

**Issue by manzke** [gesund-zusammen/gesund-zusammen.github.io#48]
We should add a part of our twitter stream to our page

**Comment by chachiludu** [comment]
Just added an option over figma file on the landing page, after Sharing is caring. If it's too intricated for now we can place the feed that tw provides and then change to something like suggested. But the structure we can maintain it.

**Comment by ajantsch** [comment]
@chachiludu do you think any of the options (maybe with some customizations) shown in https://saurabhnemade.github.io/react-twitter-embed/?path=/story/twitter-timeline-embed--timeline-profile-with-screen-name would be feasible?

**Comment by chachiludu** [comment]
Can we use this one please? Thanks!
https://saurabhnemade.github.io/react-twitter-embed/?path=/story/twitter-timeline-embed--timeline-url-with-list-url

**Comment by ajantsch** [comment]
@chachiludu WDYT?

<img width="1281" alt="Screenshot 2020-04-07 13 36 59" src="https://user-images.githubusercontent.com/3246420/78664727-e47cb780-78d4-11ea-9247-707694da65cf.png">

**Comment by manzke** [comment]
pls don't use the dark blue.

**Comment by chachiludu** [comment]
Why no dark blue?

**Comment by ajantsch** [comment]
Choose wisely

<img width="1282" alt="Screenshot 2020-04-07 13 47 07" src="https://user-images.githubusercontent.com/3246420/78665571-4c7fcd80-78d6-11ea-85ef-b4db7695732f.png">

**Comment by manzke** [comment]
actual color looks far more friendly. we should think about the title if really needed. the actual implementation looks quite noisy (boxes not aligned , one has a subtitle, ...)

**Comment by ajantsch** [comment]
You guys tell me. Aligning it vertically with the share-link box is not easily possible.

**Comment by chachiludu** [comment]
@manzke I'll write you over slack and we sort this, but it has a why the dark blue for visibility. Andy gives us a few minutes to solve this so you don't come and go
