### ISSUE TITLE
Replace toggle with a real language selector

### ISSUE THREAD

**Issue by manzke** [gesund-zusammen/gesund-zusammen.github.io#58]

**Comment by manzke** [comment]
Probably related to https://github.com/gesund-zusammen/gesund-zusammen.github.io/commit/f055826b33e7fc3b40a907a4213e3c16e292d45b

**Comment by chachiludu** [comment]
Can we make it a drop down? So in case by any chance we extend the languages we can keep on adding instead of these too? Or there's no chance we add more langues @manzke
