### ISSUE TITLE
Section in the Landing Page for the Release

### ISSUE THREAD

**Issue by manzke** [gesund-zusammen/gesund-zusammen.github.io#62]
Add a section in the landing page for the upcoming app release. Don't publish it yet!

**Comment by chachiludu** [comment]
Edit is on figma below the actual landing page named as Landing GZ EDIT

**Comment by manzke** [comment]
Re-opened because it still needs to be implemented. Please post the screenshot. :)

**Comment by chachiludu** [comment]
okay, please like we mentioned before check for the text of the added of IchHabs since it's a placeholder from what we had before

**Comment by chachiludu** [comment]
Please use the menu like Iris suggested that expands, I attach a screenshot (it's over QA page on figma)
![Landingpage_menumobile](https://user-images.githubusercontent.com/62764246/79206547-c74d6900-7e3f-11ea-93ca-214d5d4263da.png)
<img width="1440" alt="Landing gesund Zusammen EDIT" src="https://user-images.githubusercontent.com/62764246/79206667-f6fc7100-7e3f-11ea-9b9f-c34d5222c865.png">
<img width="375" alt="LandinGZ_mobile" src="https://user-images.githubusercontent.com/62764246/79206683-fc59bb80-7e3f-11ea-9497-cfb127b09cd6.png">

**Comment by manzke** [comment]
I'm going to split up, because this ticket is just about the release of the app :)

Btw: a nice read about language switched: https://usersnap.com/blog/design-language-switch/ -> don't use flags :)

**Comment by chachiludu** [comment]
Then we maintain the design without a flag, I'll edit it over the figma file
