### ISSUE TITLE
Redesign main text of landing page

### ISSUE THREAD

**Issue by manzke** [gesund-zusammen/gesund-zusammen.github.io#64]
I think it is time to improve our design of our landing page. Also in relation to #63 and #62 

<img width="1272" alt="Screenshot 2020-04-02 at 16 49 19" src="https://user-images.githubusercontent.com/339804/78263296-0d323500-7502-11ea-82a7-a703531bd284.png">

vs

<img width="1581" alt="Screenshot 2020-04-02 at 17 02 58" src="https://user-images.githubusercontent.com/339804/78264772-e248e080-7503-11ea-8abe-78b6f0176d2d.png">
<img width="1550" alt="Screenshot 2020-04-02 at 17 03 05" src="https://user-images.githubusercontent.com/339804/78264758-de1cc300-7503-11ea-976d-6840bf13f73b.png">

**Comment by chachiludu** [comment]
We should add, over the text on the hero image of the landing, something evoking that we are all together for this, I'll create a suggestion over figma but think about it. I mean the name says it but reinforce the message is always good. 
What do you think @manzke ?
